// Code generated by Kitex v0.15.2. DO NOT EDIT.

package itemservice

import (
	"context"
	exclusive_base_qz "exclusive_base_qz/kitex_gen/exclusive_base_qz"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommonLogin(ctx context.Context, req *exclusive_base_qz.CommonLoginRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonLoginResponse, err error)
	CommonUpdateUserInfo(ctx context.Context, req *exclusive_base_qz.CommonUpdateUserInfoRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonUpdateUserInfoResponse, err error)
	CommonSignOut(ctx context.Context, req *exclusive_base_qz.CommonSignOutRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonSignOutResponse, err error)
	CreateIncome(ctx context.Context, req *exclusive_base_qz.CreateIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CreateIncomeResponse, err error)
	UpdateIncome(ctx context.Context, req *exclusive_base_qz.UpdateIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.UpdateIncomeResponse, err error)
	DeleteIncome(ctx context.Context, req *exclusive_base_qz.DeleteIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.DeleteIncomeResponse, err error)
	QueryIncome(ctx context.Context, req *exclusive_base_qz.QueryIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.QueryIncomeResponse, err error)
	CreateDiary(ctx context.Context, req *exclusive_base_qz.CreateDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CreateDiaryResponse, err error)
	UpdateDiary(ctx context.Context, req *exclusive_base_qz.UpdateDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.UpdateDiaryResponse, err error)
	DeleteDiary(ctx context.Context, req *exclusive_base_qz.DeleteDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.DeleteDiaryResponse, err error)
	QueryDiary(ctx context.Context, req *exclusive_base_qz.QueryDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.QueryDiaryResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kItemServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kItemServiceClient struct {
	*kClient
}

func (p *kItemServiceClient) CommonLogin(ctx context.Context, req *exclusive_base_qz.CommonLoginRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommonLogin(ctx, req)
}

func (p *kItemServiceClient) CommonUpdateUserInfo(ctx context.Context, req *exclusive_base_qz.CommonUpdateUserInfoRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonUpdateUserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommonUpdateUserInfo(ctx, req)
}

func (p *kItemServiceClient) CommonSignOut(ctx context.Context, req *exclusive_base_qz.CommonSignOutRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CommonSignOutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommonSignOut(ctx, req)
}

func (p *kItemServiceClient) CreateIncome(ctx context.Context, req *exclusive_base_qz.CreateIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CreateIncomeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateIncome(ctx, req)
}

func (p *kItemServiceClient) UpdateIncome(ctx context.Context, req *exclusive_base_qz.UpdateIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.UpdateIncomeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateIncome(ctx, req)
}

func (p *kItemServiceClient) DeleteIncome(ctx context.Context, req *exclusive_base_qz.DeleteIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.DeleteIncomeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteIncome(ctx, req)
}

func (p *kItemServiceClient) QueryIncome(ctx context.Context, req *exclusive_base_qz.QueryIncomeRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.QueryIncomeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryIncome(ctx, req)
}

func (p *kItemServiceClient) CreateDiary(ctx context.Context, req *exclusive_base_qz.CreateDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.CreateDiaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateDiary(ctx, req)
}

func (p *kItemServiceClient) UpdateDiary(ctx context.Context, req *exclusive_base_qz.UpdateDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.UpdateDiaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDiary(ctx, req)
}

func (p *kItemServiceClient) DeleteDiary(ctx context.Context, req *exclusive_base_qz.DeleteDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.DeleteDiaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDiary(ctx, req)
}

func (p *kItemServiceClient) QueryDiary(ctx context.Context, req *exclusive_base_qz.QueryDiaryRequest, callOptions ...callopt.Option) (r *exclusive_base_qz.QueryDiaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryDiary(ctx, req)
}
