// Code generated by Kitex v0.15.2. DO NOT EDIT.

package itemservice

import (
	"context"
	"errors"
	exclusive_base_qz "exclusive_base_qz/kitex_gen/exclusive_base_qz"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CommonLogin": kitex.NewMethodInfo(
		commonLoginHandler,
		newItemServiceCommonLoginArgs,
		newItemServiceCommonLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommonIsLogin": kitex.NewMethodInfo(
		commonIsLoginHandler,
		newItemServiceCommonIsLoginArgs,
		newItemServiceCommonIsLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommonUpdateUserInfo": kitex.NewMethodInfo(
		commonUpdateUserInfoHandler,
		newItemServiceCommonUpdateUserInfoArgs,
		newItemServiceCommonUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommonSignOut": kitex.NewMethodInfo(
		commonSignOutHandler,
		newItemServiceCommonSignOutArgs,
		newItemServiceCommonSignOutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateIncome": kitex.NewMethodInfo(
		createIncomeHandler,
		newItemServiceCreateIncomeArgs,
		newItemServiceCreateIncomeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateIncome": kitex.NewMethodInfo(
		updateIncomeHandler,
		newItemServiceUpdateIncomeArgs,
		newItemServiceUpdateIncomeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteIncome": kitex.NewMethodInfo(
		deleteIncomeHandler,
		newItemServiceDeleteIncomeArgs,
		newItemServiceDeleteIncomeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryIncome": kitex.NewMethodInfo(
		queryIncomeHandler,
		newItemServiceQueryIncomeArgs,
		newItemServiceQueryIncomeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateDiary": kitex.NewMethodInfo(
		createDiaryHandler,
		newItemServiceCreateDiaryArgs,
		newItemServiceCreateDiaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDiary": kitex.NewMethodInfo(
		updateDiaryHandler,
		newItemServiceUpdateDiaryArgs,
		newItemServiceUpdateDiaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteDiary": kitex.NewMethodInfo(
		deleteDiaryHandler,
		newItemServiceDeleteDiaryArgs,
		newItemServiceDeleteDiaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryDiary": kitex.NewMethodInfo(
		queryDiaryHandler,
		newItemServiceQueryDiaryArgs,
		newItemServiceQueryDiaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	itemServiceServiceInfo                = NewServiceInfo()
	itemServiceServiceInfoForClient       = NewServiceInfoForClient()
	itemServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return itemServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return itemServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return itemServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ItemService"
	handlerType := (*exclusive_base_qz.ItemService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "exclusive_base_qz",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func commonLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCommonLoginArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCommonLoginResult)
	success, err := handler.(exclusive_base_qz.ItemService).CommonLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCommonLoginArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCommonLoginArgs()
}

func newItemServiceCommonLoginResult() interface{} {
	return exclusive_base_qz.NewItemServiceCommonLoginResult()
}

func commonIsLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCommonIsLoginArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCommonIsLoginResult)
	success, err := handler.(exclusive_base_qz.ItemService).CommonIsLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCommonIsLoginArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCommonIsLoginArgs()
}

func newItemServiceCommonIsLoginResult() interface{} {
	return exclusive_base_qz.NewItemServiceCommonIsLoginResult()
}

func commonUpdateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCommonUpdateUserInfoArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCommonUpdateUserInfoResult)
	success, err := handler.(exclusive_base_qz.ItemService).CommonUpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCommonUpdateUserInfoArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCommonUpdateUserInfoArgs()
}

func newItemServiceCommonUpdateUserInfoResult() interface{} {
	return exclusive_base_qz.NewItemServiceCommonUpdateUserInfoResult()
}

func commonSignOutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCommonSignOutArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCommonSignOutResult)
	success, err := handler.(exclusive_base_qz.ItemService).CommonSignOut(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCommonSignOutArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCommonSignOutArgs()
}

func newItemServiceCommonSignOutResult() interface{} {
	return exclusive_base_qz.NewItemServiceCommonSignOutResult()
}

func createIncomeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCreateIncomeArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCreateIncomeResult)
	success, err := handler.(exclusive_base_qz.ItemService).CreateIncome(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCreateIncomeArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCreateIncomeArgs()
}

func newItemServiceCreateIncomeResult() interface{} {
	return exclusive_base_qz.NewItemServiceCreateIncomeResult()
}

func updateIncomeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceUpdateIncomeArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceUpdateIncomeResult)
	success, err := handler.(exclusive_base_qz.ItemService).UpdateIncome(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceUpdateIncomeArgs() interface{} {
	return exclusive_base_qz.NewItemServiceUpdateIncomeArgs()
}

func newItemServiceUpdateIncomeResult() interface{} {
	return exclusive_base_qz.NewItemServiceUpdateIncomeResult()
}

func deleteIncomeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceDeleteIncomeArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceDeleteIncomeResult)
	success, err := handler.(exclusive_base_qz.ItemService).DeleteIncome(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceDeleteIncomeArgs() interface{} {
	return exclusive_base_qz.NewItemServiceDeleteIncomeArgs()
}

func newItemServiceDeleteIncomeResult() interface{} {
	return exclusive_base_qz.NewItemServiceDeleteIncomeResult()
}

func queryIncomeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceQueryIncomeArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceQueryIncomeResult)
	success, err := handler.(exclusive_base_qz.ItemService).QueryIncome(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceQueryIncomeArgs() interface{} {
	return exclusive_base_qz.NewItemServiceQueryIncomeArgs()
}

func newItemServiceQueryIncomeResult() interface{} {
	return exclusive_base_qz.NewItemServiceQueryIncomeResult()
}

func createDiaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceCreateDiaryArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceCreateDiaryResult)
	success, err := handler.(exclusive_base_qz.ItemService).CreateDiary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceCreateDiaryArgs() interface{} {
	return exclusive_base_qz.NewItemServiceCreateDiaryArgs()
}

func newItemServiceCreateDiaryResult() interface{} {
	return exclusive_base_qz.NewItemServiceCreateDiaryResult()
}

func updateDiaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceUpdateDiaryArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceUpdateDiaryResult)
	success, err := handler.(exclusive_base_qz.ItemService).UpdateDiary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceUpdateDiaryArgs() interface{} {
	return exclusive_base_qz.NewItemServiceUpdateDiaryArgs()
}

func newItemServiceUpdateDiaryResult() interface{} {
	return exclusive_base_qz.NewItemServiceUpdateDiaryResult()
}

func deleteDiaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceDeleteDiaryArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceDeleteDiaryResult)
	success, err := handler.(exclusive_base_qz.ItemService).DeleteDiary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceDeleteDiaryArgs() interface{} {
	return exclusive_base_qz.NewItemServiceDeleteDiaryArgs()
}

func newItemServiceDeleteDiaryResult() interface{} {
	return exclusive_base_qz.NewItemServiceDeleteDiaryResult()
}

func queryDiaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*exclusive_base_qz.ItemServiceQueryDiaryArgs)
	realResult := result.(*exclusive_base_qz.ItemServiceQueryDiaryResult)
	success, err := handler.(exclusive_base_qz.ItemService).QueryDiary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceQueryDiaryArgs() interface{} {
	return exclusive_base_qz.NewItemServiceQueryDiaryArgs()
}

func newItemServiceQueryDiaryResult() interface{} {
	return exclusive_base_qz.NewItemServiceQueryDiaryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CommonLogin(ctx context.Context, req *exclusive_base_qz.CommonLoginRequest) (r *exclusive_base_qz.CommonLoginResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCommonLoginArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCommonLoginResult
	if err = p.c.Call(ctx, "CommonLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommonIsLogin(ctx context.Context, req *exclusive_base_qz.CommonIsLoginRequest) (r *exclusive_base_qz.CommonIsLoginResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCommonIsLoginArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCommonIsLoginResult
	if err = p.c.Call(ctx, "CommonIsLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommonUpdateUserInfo(ctx context.Context, req *exclusive_base_qz.CommonUpdateUserInfoRequest) (r *exclusive_base_qz.CommonUpdateUserInfoResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCommonUpdateUserInfoArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCommonUpdateUserInfoResult
	if err = p.c.Call(ctx, "CommonUpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommonSignOut(ctx context.Context, req *exclusive_base_qz.CommonSignOutRequest) (r *exclusive_base_qz.CommonSignOutResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCommonSignOutArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCommonSignOutResult
	if err = p.c.Call(ctx, "CommonSignOut", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateIncome(ctx context.Context, req *exclusive_base_qz.CreateIncomeRequest) (r *exclusive_base_qz.CreateIncomeResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCreateIncomeArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCreateIncomeResult
	if err = p.c.Call(ctx, "CreateIncome", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateIncome(ctx context.Context, req *exclusive_base_qz.UpdateIncomeRequest) (r *exclusive_base_qz.UpdateIncomeResponse, err error) {
	var _args exclusive_base_qz.ItemServiceUpdateIncomeArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceUpdateIncomeResult
	if err = p.c.Call(ctx, "UpdateIncome", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteIncome(ctx context.Context, req *exclusive_base_qz.DeleteIncomeRequest) (r *exclusive_base_qz.DeleteIncomeResponse, err error) {
	var _args exclusive_base_qz.ItemServiceDeleteIncomeArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceDeleteIncomeResult
	if err = p.c.Call(ctx, "DeleteIncome", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryIncome(ctx context.Context, req *exclusive_base_qz.QueryIncomeRequest) (r *exclusive_base_qz.QueryIncomeResponse, err error) {
	var _args exclusive_base_qz.ItemServiceQueryIncomeArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceQueryIncomeResult
	if err = p.c.Call(ctx, "QueryIncome", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateDiary(ctx context.Context, req *exclusive_base_qz.CreateDiaryRequest) (r *exclusive_base_qz.CreateDiaryResponse, err error) {
	var _args exclusive_base_qz.ItemServiceCreateDiaryArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceCreateDiaryResult
	if err = p.c.Call(ctx, "CreateDiary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDiary(ctx context.Context, req *exclusive_base_qz.UpdateDiaryRequest) (r *exclusive_base_qz.UpdateDiaryResponse, err error) {
	var _args exclusive_base_qz.ItemServiceUpdateDiaryArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceUpdateDiaryResult
	if err = p.c.Call(ctx, "UpdateDiary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteDiary(ctx context.Context, req *exclusive_base_qz.DeleteDiaryRequest) (r *exclusive_base_qz.DeleteDiaryResponse, err error) {
	var _args exclusive_base_qz.ItemServiceDeleteDiaryArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceDeleteDiaryResult
	if err = p.c.Call(ctx, "DeleteDiary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryDiary(ctx context.Context, req *exclusive_base_qz.QueryDiaryRequest) (r *exclusive_base_qz.QueryDiaryResponse, err error) {
	var _args exclusive_base_qz.ItemServiceQueryDiaryArgs
	_args.Req = req
	var _result exclusive_base_qz.ItemServiceQueryDiaryResult
	if err = p.c.Call(ctx, "QueryDiary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
