// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package qatools

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type PriceTag int64

const (
	PriceTag_NotSupport     PriceTag = -2
	PriceTag_NoSameSku      PriceTag = 1
	PriceTag_MinPriceSku    PriceTag = 2
	PriceTag_NotMinPriceSku PriceTag = 3
)

func (p PriceTag) String() string {
	switch p {
	case PriceTag_NotSupport:
		return "NotSupport"
	case PriceTag_NoSameSku:
		return "NoSameSku"
	case PriceTag_MinPriceSku:
		return "MinPriceSku"
	case PriceTag_NotMinPriceSku:
		return "NotMinPriceSku"
	}
	return "<UNSET>"
}

func PriceTagFromString(s string) (PriceTag, error) {
	switch s {
	case "NotSupport":
		return PriceTag_NotSupport, nil
	case "NoSameSku":
		return PriceTag_NoSameSku, nil
	case "MinPriceSku":
		return PriceTag_MinPriceSku, nil
	case "NotMinPriceSku":
		return PriceTag_NotMinPriceSku, nil
	}
	return PriceTag(0), fmt.Errorf("not a valid PriceTag string")
}

func PriceTagPtr(v PriceTag) *PriceTag { return &v }
func (p *PriceTag) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PriceTag(result.Int64)
	return
}

func (p *PriceTag) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type PriceType int64

const (
	PriceType_OutLowestOnlinePrice            PriceType = 1
	PriceType_OutLowestSupplyPrice            PriceType = 2
	PriceType_OutSingleBuyPrice               PriceType = 3
	PriceType_OutSingleSupplyPrice            PriceType = 4
	PriceType_InnerPrice                      PriceType = 5
	PriceType_LowestSameProduct30dPriceOnline PriceType = 6
	PriceType_NoSupport                       PriceType = 7
)

func (p PriceType) String() string {
	switch p {
	case PriceType_OutLowestOnlinePrice:
		return "OutLowestOnlinePrice"
	case PriceType_OutLowestSupplyPrice:
		return "OutLowestSupplyPrice"
	case PriceType_OutSingleBuyPrice:
		return "OutSingleBuyPrice"
	case PriceType_OutSingleSupplyPrice:
		return "OutSingleSupplyPrice"
	case PriceType_InnerPrice:
		return "InnerPrice"
	case PriceType_LowestSameProduct30dPriceOnline:
		return "LowestSameProduct30dPriceOnline"
	case PriceType_NoSupport:
		return "NoSupport"
	}
	return "<UNSET>"
}

func PriceTypeFromString(s string) (PriceType, error) {
	switch s {
	case "OutLowestOnlinePrice":
		return PriceType_OutLowestOnlinePrice, nil
	case "OutLowestSupplyPrice":
		return PriceType_OutLowestSupplyPrice, nil
	case "OutSingleBuyPrice":
		return PriceType_OutSingleBuyPrice, nil
	case "OutSingleSupplyPrice":
		return PriceType_OutSingleSupplyPrice, nil
	case "InnerPrice":
		return PriceType_InnerPrice, nil
	case "LowestSameProduct30dPriceOnline":
		return PriceType_LowestSameProduct30dPriceOnline, nil
	case "NoSupport":
		return PriceType_NoSupport, nil
	}
	return PriceType(0), fmt.Errorf("not a valid PriceType string")
}

func PriceTypePtr(v PriceType) *PriceType { return &v }
func (p *PriceType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PriceType(result.Int64)
	return
}

func (p *PriceType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RoleType int64

const (
	RoleType_Shop     RoleType = 1
	RoleType_Author   RoleType = 2
	RoleType_Operator RoleType = 3
)

func (p RoleType) String() string {
	switch p {
	case RoleType_Shop:
		return "Shop"
	case RoleType_Author:
		return "Author"
	case RoleType_Operator:
		return "Operator"
	}
	return "<UNSET>"
}

func RoleTypeFromString(s string) (RoleType, error) {
	switch s {
	case "Shop":
		return RoleType_Shop, nil
	case "Author":
		return RoleType_Author, nil
	case "Operator":
		return RoleType_Operator, nil
	}
	return RoleType(0), fmt.Errorf("not a valid RoleType string")
}

func RoleTypePtr(v RoleType) *RoleType { return &v }
func (p *RoleType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RoleType(result.Int64)
	return
}

func (p *RoleType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type PriceObject int64

const (
	PriceObject_ApplyPrice    PriceObject = 1
	PriceObject_EstimatePrice PriceObject = 2
)

func (p PriceObject) String() string {
	switch p {
	case PriceObject_ApplyPrice:
		return "ApplyPrice"
	case PriceObject_EstimatePrice:
		return "EstimatePrice"
	}
	return "<UNSET>"
}

func PriceObjectFromString(s string) (PriceObject, error) {
	switch s {
	case "ApplyPrice":
		return PriceObject_ApplyPrice, nil
	case "EstimatePrice":
		return PriceObject_EstimatePrice, nil
	}
	return PriceObject(0), fmt.Errorf("not a valid PriceObject string")
}

func PriceObjectPtr(v PriceObject) *PriceObject { return &v }
func (p *PriceObject) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PriceObject(result.Int64)
	return
}

func (p *PriceObject) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SignRecordStatus int64

const (
	SignRecordStatus_unknown                   SignRecordStatus = 0
	SignRecordStatus_draft                     SignRecordStatus = 1
	SignRecordStatus_wait_first_audit          SignRecordStatus = 2
	SignRecordStatus_wait_second_audit         SignRecordStatus = 3
	SignRecordStatus_wait_third_audit          SignRecordStatus = 4
	SignRecordStatus_apply_succeed             SignRecordStatus = 6
	SignRecordStatus_audit_rejected            SignRecordStatus = 7
	SignRecordStatus_wait_deposit              SignRecordStatus = 5
	SignRecordStatus_wait_author_confirm       SignRecordStatus = 8
	SignRecordStatus_canceled                  SignRecordStatus = 11
	SignRecordStatus_wait_publish              SignRecordStatus = 12
	SignRecordStatus_wait_set_subsidy          SignRecordStatus = 13
	SignRecordStatus_subsidy_audit_in_progress SignRecordStatus = 14
	SignRecordStatus_wait_set_schedule         SignRecordStatus = 15
	SignRecordStatus_price_risk_wait_audit     SignRecordStatus = 16
	SignRecordStatus_wait_bid_publish          SignRecordStatus = 17
	SignRecordStatus_draft_with_algo_schedule  SignRecordStatus = 18
)

func (p SignRecordStatus) String() string {
	switch p {
	case SignRecordStatus_unknown:
		return "unknown"
	case SignRecordStatus_draft:
		return "draft"
	case SignRecordStatus_wait_first_audit:
		return "wait_first_audit"
	case SignRecordStatus_wait_second_audit:
		return "wait_second_audit"
	case SignRecordStatus_wait_third_audit:
		return "wait_third_audit"
	case SignRecordStatus_apply_succeed:
		return "apply_succeed"
	case SignRecordStatus_audit_rejected:
		return "audit_rejected"
	case SignRecordStatus_wait_deposit:
		return "wait_deposit"
	case SignRecordStatus_wait_author_confirm:
		return "wait_author_confirm"
	case SignRecordStatus_canceled:
		return "canceled"
	case SignRecordStatus_wait_publish:
		return "wait_publish"
	case SignRecordStatus_wait_set_subsidy:
		return "wait_set_subsidy"
	case SignRecordStatus_subsidy_audit_in_progress:
		return "subsidy_audit_in_progress"
	case SignRecordStatus_wait_set_schedule:
		return "wait_set_schedule"
	case SignRecordStatus_price_risk_wait_audit:
		return "price_risk_wait_audit"
	case SignRecordStatus_wait_bid_publish:
		return "wait_bid_publish"
	case SignRecordStatus_draft_with_algo_schedule:
		return "draft_with_algo_schedule"
	}
	return "<UNSET>"
}

func SignRecordStatusFromString(s string) (SignRecordStatus, error) {
	switch s {
	case "unknown":
		return SignRecordStatus_unknown, nil
	case "draft":
		return SignRecordStatus_draft, nil
	case "wait_first_audit":
		return SignRecordStatus_wait_first_audit, nil
	case "wait_second_audit":
		return SignRecordStatus_wait_second_audit, nil
	case "wait_third_audit":
		return SignRecordStatus_wait_third_audit, nil
	case "apply_succeed":
		return SignRecordStatus_apply_succeed, nil
	case "audit_rejected":
		return SignRecordStatus_audit_rejected, nil
	case "wait_deposit":
		return SignRecordStatus_wait_deposit, nil
	case "wait_author_confirm":
		return SignRecordStatus_wait_author_confirm, nil
	case "canceled":
		return SignRecordStatus_canceled, nil
	case "wait_publish":
		return SignRecordStatus_wait_publish, nil
	case "wait_set_subsidy":
		return SignRecordStatus_wait_set_subsidy, nil
	case "subsidy_audit_in_progress":
		return SignRecordStatus_subsidy_audit_in_progress, nil
	case "wait_set_schedule":
		return SignRecordStatus_wait_set_schedule, nil
	case "price_risk_wait_audit":
		return SignRecordStatus_price_risk_wait_audit, nil
	case "wait_bid_publish":
		return SignRecordStatus_wait_bid_publish, nil
	case "draft_with_algo_schedule":
		return SignRecordStatus_draft_with_algo_schedule, nil
	}
	return SignRecordStatus(0), fmt.Errorf("not a valid SignRecordStatus string")
}

func SignRecordStatusPtr(v SignRecordStatus) *SignRecordStatus { return &v }
func (p *SignRecordStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SignRecordStatus(result.Int64)
	return
}

func (p *SignRecordStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
