// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package exclusive_base_qz

import (
	"context"
	"exclusive_base_qz/kitex_gen/base"
	"fmt"
)

type CommonLoginRequest struct {
	User     *string `thrift:"user,1,optional" frugal:"1,optional,string" json:"user,omitempty"`
	Password *string `thrift:"password,2,optional" frugal:"2,optional,string" json:"password,omitempty"`
	Token    *string `thrift:"token,3,optional" frugal:"3,optional,string" json:"token,omitempty"`
}

func NewCommonLoginRequest() *CommonLoginRequest {
	return &CommonLoginRequest{}
}

func (p *CommonLoginRequest) InitDefault() {
}

var CommonLoginRequest_User_DEFAULT string

func (p *CommonLoginRequest) GetUser() (v string) {
	if !p.IsSetUser() {
		return CommonLoginRequest_User_DEFAULT
	}
	return *p.User
}

var CommonLoginRequest_Password_DEFAULT string

func (p *CommonLoginRequest) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return CommonLoginRequest_Password_DEFAULT
	}
	return *p.Password
}

var CommonLoginRequest_Token_DEFAULT string

func (p *CommonLoginRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CommonLoginRequest_Token_DEFAULT
	}
	return *p.Token
}
func (p *CommonLoginRequest) SetUser(val *string) {
	p.User = val
}
func (p *CommonLoginRequest) SetPassword(val *string) {
	p.Password = val
}
func (p *CommonLoginRequest) SetToken(val *string) {
	p.Token = val
}

func (p *CommonLoginRequest) IsSetUser() bool {
	return p.User != nil
}

func (p *CommonLoginRequest) IsSetPassword() bool {
	return p.Password != nil
}

func (p *CommonLoginRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CommonLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonLoginRequest(%+v)", *p)
}

var fieldIDToName_CommonLoginRequest = map[int16]string{
	1: "user",
	2: "password",
	3: "token",
}

type CommonLoginResponse struct {
	Token    *string        `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCommonLoginResponse() *CommonLoginResponse {
	return &CommonLoginResponse{}
}

func (p *CommonLoginResponse) InitDefault() {
}

var CommonLoginResponse_Token_DEFAULT string

func (p *CommonLoginResponse) GetToken() (v string) {
	if !p.IsSetToken() {
		return CommonLoginResponse_Token_DEFAULT
	}
	return *p.Token
}

var CommonLoginResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CommonLoginResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CommonLoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CommonLoginResponse) SetToken(val *string) {
	p.Token = val
}
func (p *CommonLoginResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CommonLoginResponse) IsSetToken() bool {
	return p.Token != nil
}

func (p *CommonLoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CommonLoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonLoginResponse(%+v)", *p)
}

var fieldIDToName_CommonLoginResponse = map[int16]string{
	1:   "token",
	255: "BaseResp",
}

type CommonIsLoginRequest struct {
	Token *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
}

func NewCommonIsLoginRequest() *CommonIsLoginRequest {
	return &CommonIsLoginRequest{}
}

func (p *CommonIsLoginRequest) InitDefault() {
}

var CommonIsLoginRequest_Token_DEFAULT string

func (p *CommonIsLoginRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CommonIsLoginRequest_Token_DEFAULT
	}
	return *p.Token
}
func (p *CommonIsLoginRequest) SetToken(val *string) {
	p.Token = val
}

func (p *CommonIsLoginRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CommonIsLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonIsLoginRequest(%+v)", *p)
}

var fieldIDToName_CommonIsLoginRequest = map[int16]string{
	1: "token",
}

type CommonIsLoginResponse struct {
	IsLogin  *string        `thrift:"isLogin,1,optional" frugal:"1,optional,string" json:"isLogin,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCommonIsLoginResponse() *CommonIsLoginResponse {
	return &CommonIsLoginResponse{}
}

func (p *CommonIsLoginResponse) InitDefault() {
}

var CommonIsLoginResponse_IsLogin_DEFAULT string

func (p *CommonIsLoginResponse) GetIsLogin() (v string) {
	if !p.IsSetIsLogin() {
		return CommonIsLoginResponse_IsLogin_DEFAULT
	}
	return *p.IsLogin
}

var CommonIsLoginResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CommonIsLoginResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CommonIsLoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CommonIsLoginResponse) SetIsLogin(val *string) {
	p.IsLogin = val
}
func (p *CommonIsLoginResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CommonIsLoginResponse) IsSetIsLogin() bool {
	return p.IsLogin != nil
}

func (p *CommonIsLoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CommonIsLoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonIsLoginResponse(%+v)", *p)
}

var fieldIDToName_CommonIsLoginResponse = map[int16]string{
	1:   "isLogin",
	255: "BaseResp",
}

type CommonUpdateUserInfoRequest struct {
	Ping         *string `thrift:"ping,1,optional" frugal:"1,optional,string" json:"ping,omitempty"`
	NewPassword_ *string `thrift:"new_password,2,optional" frugal:"2,optional,string" json:"new_password,omitempty"`
	User         *string `thrift:"user,3,optional" frugal:"3,optional,string" json:"user,omitempty"`
	Token        *string `thrift:"token,4,optional" frugal:"4,optional,string" json:"token,omitempty"`
}

func NewCommonUpdateUserInfoRequest() *CommonUpdateUserInfoRequest {
	return &CommonUpdateUserInfoRequest{}
}

func (p *CommonUpdateUserInfoRequest) InitDefault() {
}

var CommonUpdateUserInfoRequest_Ping_DEFAULT string

func (p *CommonUpdateUserInfoRequest) GetPing() (v string) {
	if !p.IsSetPing() {
		return CommonUpdateUserInfoRequest_Ping_DEFAULT
	}
	return *p.Ping
}

var CommonUpdateUserInfoRequest_NewPassword__DEFAULT string

func (p *CommonUpdateUserInfoRequest) GetNewPassword_() (v string) {
	if !p.IsSetNewPassword_() {
		return CommonUpdateUserInfoRequest_NewPassword__DEFAULT
	}
	return *p.NewPassword_
}

var CommonUpdateUserInfoRequest_User_DEFAULT string

func (p *CommonUpdateUserInfoRequest) GetUser() (v string) {
	if !p.IsSetUser() {
		return CommonUpdateUserInfoRequest_User_DEFAULT
	}
	return *p.User
}

var CommonUpdateUserInfoRequest_Token_DEFAULT string

func (p *CommonUpdateUserInfoRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CommonUpdateUserInfoRequest_Token_DEFAULT
	}
	return *p.Token
}
func (p *CommonUpdateUserInfoRequest) SetPing(val *string) {
	p.Ping = val
}
func (p *CommonUpdateUserInfoRequest) SetNewPassword_(val *string) {
	p.NewPassword_ = val
}
func (p *CommonUpdateUserInfoRequest) SetUser(val *string) {
	p.User = val
}
func (p *CommonUpdateUserInfoRequest) SetToken(val *string) {
	p.Token = val
}

func (p *CommonUpdateUserInfoRequest) IsSetPing() bool {
	return p.Ping != nil
}

func (p *CommonUpdateUserInfoRequest) IsSetNewPassword_() bool {
	return p.NewPassword_ != nil
}

func (p *CommonUpdateUserInfoRequest) IsSetUser() bool {
	return p.User != nil
}

func (p *CommonUpdateUserInfoRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CommonUpdateUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonUpdateUserInfoRequest(%+v)", *p)
}

var fieldIDToName_CommonUpdateUserInfoRequest = map[int16]string{
	1: "ping",
	2: "new_password",
	3: "user",
	4: "token",
}

type CommonUpdateUserInfoResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCommonUpdateUserInfoResponse() *CommonUpdateUserInfoResponse {
	return &CommonUpdateUserInfoResponse{}
}

func (p *CommonUpdateUserInfoResponse) InitDefault() {
}

var CommonUpdateUserInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CommonUpdateUserInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CommonUpdateUserInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CommonUpdateUserInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CommonUpdateUserInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CommonUpdateUserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonUpdateUserInfoResponse(%+v)", *p)
}

var fieldIDToName_CommonUpdateUserInfoResponse = map[int16]string{
	255: "BaseResp",
}

type CommonSignOutRequest struct {
	Token *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
}

func NewCommonSignOutRequest() *CommonSignOutRequest {
	return &CommonSignOutRequest{}
}

func (p *CommonSignOutRequest) InitDefault() {
}

var CommonSignOutRequest_Token_DEFAULT string

func (p *CommonSignOutRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CommonSignOutRequest_Token_DEFAULT
	}
	return *p.Token
}
func (p *CommonSignOutRequest) SetToken(val *string) {
	p.Token = val
}

func (p *CommonSignOutRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CommonSignOutRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonSignOutRequest(%+v)", *p)
}

var fieldIDToName_CommonSignOutRequest = map[int16]string{
	1: "token",
}

type CommonSignOutResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCommonSignOutResponse() *CommonSignOutResponse {
	return &CommonSignOutResponse{}
}

func (p *CommonSignOutResponse) InitDefault() {
}

var CommonSignOutResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CommonSignOutResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CommonSignOutResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CommonSignOutResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CommonSignOutResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CommonSignOutResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonSignOutResponse(%+v)", *p)
}

var fieldIDToName_CommonSignOutResponse = map[int16]string{
	255: "BaseResp",
}

type CreateIncomeRequest struct {
	Token     *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	Amount    *string `thrift:"amount,2,optional" frugal:"2,optional,string" json:"amount,omitempty"`
	SpendType *string `thrift:"spendType,3,optional" frugal:"3,optional,string" json:"spendType,omitempty"`
	SpendTime *string `thrift:"spendTime,4,optional" frugal:"4,optional,string" json:"spendTime,omitempty"`
	Remark    *string `thrift:"remark,5,optional" frugal:"5,optional,string" json:"remark,omitempty"`
}

func NewCreateIncomeRequest() *CreateIncomeRequest {
	return &CreateIncomeRequest{}
}

func (p *CreateIncomeRequest) InitDefault() {
}

var CreateIncomeRequest_Token_DEFAULT string

func (p *CreateIncomeRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CreateIncomeRequest_Token_DEFAULT
	}
	return *p.Token
}

var CreateIncomeRequest_Amount_DEFAULT string

func (p *CreateIncomeRequest) GetAmount() (v string) {
	if !p.IsSetAmount() {
		return CreateIncomeRequest_Amount_DEFAULT
	}
	return *p.Amount
}

var CreateIncomeRequest_SpendType_DEFAULT string

func (p *CreateIncomeRequest) GetSpendType() (v string) {
	if !p.IsSetSpendType() {
		return CreateIncomeRequest_SpendType_DEFAULT
	}
	return *p.SpendType
}

var CreateIncomeRequest_SpendTime_DEFAULT string

func (p *CreateIncomeRequest) GetSpendTime() (v string) {
	if !p.IsSetSpendTime() {
		return CreateIncomeRequest_SpendTime_DEFAULT
	}
	return *p.SpendTime
}

var CreateIncomeRequest_Remark_DEFAULT string

func (p *CreateIncomeRequest) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return CreateIncomeRequest_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *CreateIncomeRequest) SetToken(val *string) {
	p.Token = val
}
func (p *CreateIncomeRequest) SetAmount(val *string) {
	p.Amount = val
}
func (p *CreateIncomeRequest) SetSpendType(val *string) {
	p.SpendType = val
}
func (p *CreateIncomeRequest) SetSpendTime(val *string) {
	p.SpendTime = val
}
func (p *CreateIncomeRequest) SetRemark(val *string) {
	p.Remark = val
}

func (p *CreateIncomeRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CreateIncomeRequest) IsSetAmount() bool {
	return p.Amount != nil
}

func (p *CreateIncomeRequest) IsSetSpendType() bool {
	return p.SpendType != nil
}

func (p *CreateIncomeRequest) IsSetSpendTime() bool {
	return p.SpendTime != nil
}

func (p *CreateIncomeRequest) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *CreateIncomeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateIncomeRequest(%+v)", *p)
}

var fieldIDToName_CreateIncomeRequest = map[int16]string{
	1: "token",
	2: "amount",
	3: "spendType",
	4: "spendTime",
	5: "remark",
}

type CreateIncomeResponse struct {
	IncomeId *string        `thrift:"incomeId,1,optional" frugal:"1,optional,string" json:"incomeId,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCreateIncomeResponse() *CreateIncomeResponse {
	return &CreateIncomeResponse{}
}

func (p *CreateIncomeResponse) InitDefault() {
}

var CreateIncomeResponse_IncomeId_DEFAULT string

func (p *CreateIncomeResponse) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return CreateIncomeResponse_IncomeId_DEFAULT
	}
	return *p.IncomeId
}

var CreateIncomeResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CreateIncomeResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateIncomeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateIncomeResponse) SetIncomeId(val *string) {
	p.IncomeId = val
}
func (p *CreateIncomeResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateIncomeResponse) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *CreateIncomeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateIncomeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateIncomeResponse(%+v)", *p)
}

var fieldIDToName_CreateIncomeResponse = map[int16]string{
	1:   "incomeId",
	255: "BaseResp",
}

type UpdateIncomeRequest struct {
	Token     *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	Amount    *string `thrift:"amount,2,optional" frugal:"2,optional,string" json:"amount,omitempty"`
	SpendType *string `thrift:"spendType,3,optional" frugal:"3,optional,string" json:"spendType,omitempty"`
	SpendTime *string `thrift:"spendTime,4,optional" frugal:"4,optional,string" json:"spendTime,omitempty"`
	Remark    *string `thrift:"remark,5,optional" frugal:"5,optional,string" json:"remark,omitempty"`
	IncomeId  *string `thrift:"incomeId,6,optional" frugal:"6,optional,string" json:"incomeId,omitempty"`
}

func NewUpdateIncomeRequest() *UpdateIncomeRequest {
	return &UpdateIncomeRequest{}
}

func (p *UpdateIncomeRequest) InitDefault() {
}

var UpdateIncomeRequest_Token_DEFAULT string

func (p *UpdateIncomeRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return UpdateIncomeRequest_Token_DEFAULT
	}
	return *p.Token
}

var UpdateIncomeRequest_Amount_DEFAULT string

func (p *UpdateIncomeRequest) GetAmount() (v string) {
	if !p.IsSetAmount() {
		return UpdateIncomeRequest_Amount_DEFAULT
	}
	return *p.Amount
}

var UpdateIncomeRequest_SpendType_DEFAULT string

func (p *UpdateIncomeRequest) GetSpendType() (v string) {
	if !p.IsSetSpendType() {
		return UpdateIncomeRequest_SpendType_DEFAULT
	}
	return *p.SpendType
}

var UpdateIncomeRequest_SpendTime_DEFAULT string

func (p *UpdateIncomeRequest) GetSpendTime() (v string) {
	if !p.IsSetSpendTime() {
		return UpdateIncomeRequest_SpendTime_DEFAULT
	}
	return *p.SpendTime
}

var UpdateIncomeRequest_Remark_DEFAULT string

func (p *UpdateIncomeRequest) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return UpdateIncomeRequest_Remark_DEFAULT
	}
	return *p.Remark
}

var UpdateIncomeRequest_IncomeId_DEFAULT string

func (p *UpdateIncomeRequest) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return UpdateIncomeRequest_IncomeId_DEFAULT
	}
	return *p.IncomeId
}
func (p *UpdateIncomeRequest) SetToken(val *string) {
	p.Token = val
}
func (p *UpdateIncomeRequest) SetAmount(val *string) {
	p.Amount = val
}
func (p *UpdateIncomeRequest) SetSpendType(val *string) {
	p.SpendType = val
}
func (p *UpdateIncomeRequest) SetSpendTime(val *string) {
	p.SpendTime = val
}
func (p *UpdateIncomeRequest) SetRemark(val *string) {
	p.Remark = val
}
func (p *UpdateIncomeRequest) SetIncomeId(val *string) {
	p.IncomeId = val
}

func (p *UpdateIncomeRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *UpdateIncomeRequest) IsSetAmount() bool {
	return p.Amount != nil
}

func (p *UpdateIncomeRequest) IsSetSpendType() bool {
	return p.SpendType != nil
}

func (p *UpdateIncomeRequest) IsSetSpendTime() bool {
	return p.SpendTime != nil
}

func (p *UpdateIncomeRequest) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *UpdateIncomeRequest) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *UpdateIncomeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateIncomeRequest(%+v)", *p)
}

var fieldIDToName_UpdateIncomeRequest = map[int16]string{
	1: "token",
	2: "amount",
	3: "spendType",
	4: "spendTime",
	5: "remark",
	6: "incomeId",
}

type UpdateIncomeResponse struct {
	IncomeId *string        `thrift:"incomeId,1,optional" frugal:"1,optional,string" json:"incomeId,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewUpdateIncomeResponse() *UpdateIncomeResponse {
	return &UpdateIncomeResponse{}
}

func (p *UpdateIncomeResponse) InitDefault() {
}

var UpdateIncomeResponse_IncomeId_DEFAULT string

func (p *UpdateIncomeResponse) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return UpdateIncomeResponse_IncomeId_DEFAULT
	}
	return *p.IncomeId
}

var UpdateIncomeResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateIncomeResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateIncomeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateIncomeResponse) SetIncomeId(val *string) {
	p.IncomeId = val
}
func (p *UpdateIncomeResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateIncomeResponse) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *UpdateIncomeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateIncomeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateIncomeResponse(%+v)", *p)
}

var fieldIDToName_UpdateIncomeResponse = map[int16]string{
	1:   "incomeId",
	255: "BaseResp",
}

type DeleteIncomeRequest struct {
	Token    *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	IncomeId *string `thrift:"incomeId,2,optional" frugal:"2,optional,string" json:"incomeId,omitempty"`
}

func NewDeleteIncomeRequest() *DeleteIncomeRequest {
	return &DeleteIncomeRequest{}
}

func (p *DeleteIncomeRequest) InitDefault() {
}

var DeleteIncomeRequest_Token_DEFAULT string

func (p *DeleteIncomeRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return DeleteIncomeRequest_Token_DEFAULT
	}
	return *p.Token
}

var DeleteIncomeRequest_IncomeId_DEFAULT string

func (p *DeleteIncomeRequest) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return DeleteIncomeRequest_IncomeId_DEFAULT
	}
	return *p.IncomeId
}
func (p *DeleteIncomeRequest) SetToken(val *string) {
	p.Token = val
}
func (p *DeleteIncomeRequest) SetIncomeId(val *string) {
	p.IncomeId = val
}

func (p *DeleteIncomeRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *DeleteIncomeRequest) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *DeleteIncomeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteIncomeRequest(%+v)", *p)
}

var fieldIDToName_DeleteIncomeRequest = map[int16]string{
	1: "token",
	2: "incomeId",
}

type DeleteIncomeResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewDeleteIncomeResponse() *DeleteIncomeResponse {
	return &DeleteIncomeResponse{}
}

func (p *DeleteIncomeResponse) InitDefault() {
}

var DeleteIncomeResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteIncomeResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteIncomeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteIncomeResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteIncomeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteIncomeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteIncomeResponse(%+v)", *p)
}

var fieldIDToName_DeleteIncomeResponse = map[int16]string{
	255: "BaseResp",
}

type QueryIncomeRequest struct {
	Token          *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	MinAmount      *string `thrift:"minAmount,2,optional" frugal:"2,optional,string" json:"minAmount,omitempty"`
	MaxAmount      *string `thrift:"maxAmount,3,optional" frugal:"3,optional,string" json:"maxAmount,omitempty"`
	SpendType      *string `thrift:"spendType,4,optional" frugal:"4,optional,string" json:"spendType,omitempty"`
	SpendStartTime *string `thrift:"spendStartTime,5,optional" frugal:"5,optional,string" json:"spendStartTime,omitempty"`
	SpendEndTime   *string `thrift:"spendEndTime,6,optional" frugal:"6,optional,string" json:"spendEndTime,omitempty"`
	IncomeId       *string `thrift:"incomeId,7,optional" frugal:"7,optional,string" json:"incomeId,omitempty"`
	Remark         *string `thrift:"remark,8,optional" frugal:"8,optional,string" json:"remark,omitempty"`
	Page           *string `thrift:"page,9,optional" frugal:"9,optional,string" json:"page,omitempty"`
	Size           *string `thrift:"size,10,optional" frugal:"10,optional,string" json:"size,omitempty"`
}

func NewQueryIncomeRequest() *QueryIncomeRequest {
	return &QueryIncomeRequest{}
}

func (p *QueryIncomeRequest) InitDefault() {
}

var QueryIncomeRequest_Token_DEFAULT string

func (p *QueryIncomeRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return QueryIncomeRequest_Token_DEFAULT
	}
	return *p.Token
}

var QueryIncomeRequest_MinAmount_DEFAULT string

func (p *QueryIncomeRequest) GetMinAmount() (v string) {
	if !p.IsSetMinAmount() {
		return QueryIncomeRequest_MinAmount_DEFAULT
	}
	return *p.MinAmount
}

var QueryIncomeRequest_MaxAmount_DEFAULT string

func (p *QueryIncomeRequest) GetMaxAmount() (v string) {
	if !p.IsSetMaxAmount() {
		return QueryIncomeRequest_MaxAmount_DEFAULT
	}
	return *p.MaxAmount
}

var QueryIncomeRequest_SpendType_DEFAULT string

func (p *QueryIncomeRequest) GetSpendType() (v string) {
	if !p.IsSetSpendType() {
		return QueryIncomeRequest_SpendType_DEFAULT
	}
	return *p.SpendType
}

var QueryIncomeRequest_SpendStartTime_DEFAULT string

func (p *QueryIncomeRequest) GetSpendStartTime() (v string) {
	if !p.IsSetSpendStartTime() {
		return QueryIncomeRequest_SpendStartTime_DEFAULT
	}
	return *p.SpendStartTime
}

var QueryIncomeRequest_SpendEndTime_DEFAULT string

func (p *QueryIncomeRequest) GetSpendEndTime() (v string) {
	if !p.IsSetSpendEndTime() {
		return QueryIncomeRequest_SpendEndTime_DEFAULT
	}
	return *p.SpendEndTime
}

var QueryIncomeRequest_IncomeId_DEFAULT string

func (p *QueryIncomeRequest) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return QueryIncomeRequest_IncomeId_DEFAULT
	}
	return *p.IncomeId
}

var QueryIncomeRequest_Remark_DEFAULT string

func (p *QueryIncomeRequest) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return QueryIncomeRequest_Remark_DEFAULT
	}
	return *p.Remark
}

var QueryIncomeRequest_Page_DEFAULT string

func (p *QueryIncomeRequest) GetPage() (v string) {
	if !p.IsSetPage() {
		return QueryIncomeRequest_Page_DEFAULT
	}
	return *p.Page
}

var QueryIncomeRequest_Size_DEFAULT string

func (p *QueryIncomeRequest) GetSize() (v string) {
	if !p.IsSetSize() {
		return QueryIncomeRequest_Size_DEFAULT
	}
	return *p.Size
}
func (p *QueryIncomeRequest) SetToken(val *string) {
	p.Token = val
}
func (p *QueryIncomeRequest) SetMinAmount(val *string) {
	p.MinAmount = val
}
func (p *QueryIncomeRequest) SetMaxAmount(val *string) {
	p.MaxAmount = val
}
func (p *QueryIncomeRequest) SetSpendType(val *string) {
	p.SpendType = val
}
func (p *QueryIncomeRequest) SetSpendStartTime(val *string) {
	p.SpendStartTime = val
}
func (p *QueryIncomeRequest) SetSpendEndTime(val *string) {
	p.SpendEndTime = val
}
func (p *QueryIncomeRequest) SetIncomeId(val *string) {
	p.IncomeId = val
}
func (p *QueryIncomeRequest) SetRemark(val *string) {
	p.Remark = val
}
func (p *QueryIncomeRequest) SetPage(val *string) {
	p.Page = val
}
func (p *QueryIncomeRequest) SetSize(val *string) {
	p.Size = val
}

func (p *QueryIncomeRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *QueryIncomeRequest) IsSetMinAmount() bool {
	return p.MinAmount != nil
}

func (p *QueryIncomeRequest) IsSetMaxAmount() bool {
	return p.MaxAmount != nil
}

func (p *QueryIncomeRequest) IsSetSpendType() bool {
	return p.SpendType != nil
}

func (p *QueryIncomeRequest) IsSetSpendStartTime() bool {
	return p.SpendStartTime != nil
}

func (p *QueryIncomeRequest) IsSetSpendEndTime() bool {
	return p.SpendEndTime != nil
}

func (p *QueryIncomeRequest) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *QueryIncomeRequest) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *QueryIncomeRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *QueryIncomeRequest) IsSetSize() bool {
	return p.Size != nil
}

func (p *QueryIncomeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryIncomeRequest(%+v)", *p)
}

var fieldIDToName_QueryIncomeRequest = map[int16]string{
	1:  "token",
	2:  "minAmount",
	3:  "maxAmount",
	4:  "spendType",
	5:  "spendStartTime",
	6:  "spendEndTime",
	7:  "incomeId",
	8:  "remark",
	9:  "page",
	10: "size",
}

type QueryIncomeResponse struct {
	IncomeInfo  []*IncomeInfo  `thrift:"IncomeInfo,1,optional" frugal:"1,optional,list<IncomeInfo>" json:"IncomeInfo,omitempty"`
	Total       *string        `thrift:"total,2,optional" frugal:"2,optional,string" json:"total,omitempty"`
	IncomeCount *IncomeCount   `thrift:"IncomeCount,3,optional" frugal:"3,optional,IncomeCount" json:"IncomeCount,omitempty"`
	BaseResp    *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewQueryIncomeResponse() *QueryIncomeResponse {
	return &QueryIncomeResponse{}
}

func (p *QueryIncomeResponse) InitDefault() {
}

var QueryIncomeResponse_IncomeInfo_DEFAULT []*IncomeInfo

func (p *QueryIncomeResponse) GetIncomeInfo() (v []*IncomeInfo) {
	if !p.IsSetIncomeInfo() {
		return QueryIncomeResponse_IncomeInfo_DEFAULT
	}
	return p.IncomeInfo
}

var QueryIncomeResponse_Total_DEFAULT string

func (p *QueryIncomeResponse) GetTotal() (v string) {
	if !p.IsSetTotal() {
		return QueryIncomeResponse_Total_DEFAULT
	}
	return *p.Total
}

var QueryIncomeResponse_IncomeCount_DEFAULT *IncomeCount

func (p *QueryIncomeResponse) GetIncomeCount() (v *IncomeCount) {
	if !p.IsSetIncomeCount() {
		return QueryIncomeResponse_IncomeCount_DEFAULT
	}
	return p.IncomeCount
}

var QueryIncomeResponse_BaseResp_DEFAULT *base.BaseResp

func (p *QueryIncomeResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return QueryIncomeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *QueryIncomeResponse) SetIncomeInfo(val []*IncomeInfo) {
	p.IncomeInfo = val
}
func (p *QueryIncomeResponse) SetTotal(val *string) {
	p.Total = val
}
func (p *QueryIncomeResponse) SetIncomeCount(val *IncomeCount) {
	p.IncomeCount = val
}
func (p *QueryIncomeResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *QueryIncomeResponse) IsSetIncomeInfo() bool {
	return p.IncomeInfo != nil
}

func (p *QueryIncomeResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *QueryIncomeResponse) IsSetIncomeCount() bool {
	return p.IncomeCount != nil
}

func (p *QueryIncomeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *QueryIncomeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryIncomeResponse(%+v)", *p)
}

var fieldIDToName_QueryIncomeResponse = map[int16]string{
	1:   "IncomeInfo",
	2:   "total",
	3:   "IncomeCount",
	255: "BaseResp",
}

type IncomeInfo struct {
	Amount    *string `thrift:"amount,1,optional" frugal:"1,optional,string" json:"amount,omitempty"`
	SpendType *string `thrift:"spendType,2,optional" frugal:"2,optional,string" json:"spendType,omitempty"`
	SpendTime *string `thrift:"spendTime,3,optional" frugal:"3,optional,string" json:"spendTime,omitempty"`
	IncomeId  *string `thrift:"incomeId,4,optional" frugal:"4,optional,string" json:"incomeId,omitempty"`
	Remark    *string `thrift:"remark,5,optional" frugal:"5,optional,string" json:"remark,omitempty"`
}

func NewIncomeInfo() *IncomeInfo {
	return &IncomeInfo{}
}

func (p *IncomeInfo) InitDefault() {
}

var IncomeInfo_Amount_DEFAULT string

func (p *IncomeInfo) GetAmount() (v string) {
	if !p.IsSetAmount() {
		return IncomeInfo_Amount_DEFAULT
	}
	return *p.Amount
}

var IncomeInfo_SpendType_DEFAULT string

func (p *IncomeInfo) GetSpendType() (v string) {
	if !p.IsSetSpendType() {
		return IncomeInfo_SpendType_DEFAULT
	}
	return *p.SpendType
}

var IncomeInfo_SpendTime_DEFAULT string

func (p *IncomeInfo) GetSpendTime() (v string) {
	if !p.IsSetSpendTime() {
		return IncomeInfo_SpendTime_DEFAULT
	}
	return *p.SpendTime
}

var IncomeInfo_IncomeId_DEFAULT string

func (p *IncomeInfo) GetIncomeId() (v string) {
	if !p.IsSetIncomeId() {
		return IncomeInfo_IncomeId_DEFAULT
	}
	return *p.IncomeId
}

var IncomeInfo_Remark_DEFAULT string

func (p *IncomeInfo) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return IncomeInfo_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *IncomeInfo) SetAmount(val *string) {
	p.Amount = val
}
func (p *IncomeInfo) SetSpendType(val *string) {
	p.SpendType = val
}
func (p *IncomeInfo) SetSpendTime(val *string) {
	p.SpendTime = val
}
func (p *IncomeInfo) SetIncomeId(val *string) {
	p.IncomeId = val
}
func (p *IncomeInfo) SetRemark(val *string) {
	p.Remark = val
}

func (p *IncomeInfo) IsSetAmount() bool {
	return p.Amount != nil
}

func (p *IncomeInfo) IsSetSpendType() bool {
	return p.SpendType != nil
}

func (p *IncomeInfo) IsSetSpendTime() bool {
	return p.SpendTime != nil
}

func (p *IncomeInfo) IsSetIncomeId() bool {
	return p.IncomeId != nil
}

func (p *IncomeInfo) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *IncomeInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IncomeInfo(%+v)", *p)
}

var fieldIDToName_IncomeInfo = map[int16]string{
	1: "amount",
	2: "spendType",
	3: "spendTime",
	4: "incomeId",
	5: "remark",
}

type IncomeCount struct {
	Month map[string]string `thrift:"month,1,optional" frugal:"1,optional,map<string:string>" json:"month,omitempty"`
	Week  map[string]string `thrift:"week,2,optional" frugal:"2,optional,map<string:string>" json:"week,omitempty"`
}

func NewIncomeCount() *IncomeCount {
	return &IncomeCount{}
}

func (p *IncomeCount) InitDefault() {
}

var IncomeCount_Month_DEFAULT map[string]string

func (p *IncomeCount) GetMonth() (v map[string]string) {
	if !p.IsSetMonth() {
		return IncomeCount_Month_DEFAULT
	}
	return p.Month
}

var IncomeCount_Week_DEFAULT map[string]string

func (p *IncomeCount) GetWeek() (v map[string]string) {
	if !p.IsSetWeek() {
		return IncomeCount_Week_DEFAULT
	}
	return p.Week
}
func (p *IncomeCount) SetMonth(val map[string]string) {
	p.Month = val
}
func (p *IncomeCount) SetWeek(val map[string]string) {
	p.Week = val
}

func (p *IncomeCount) IsSetMonth() bool {
	return p.Month != nil
}

func (p *IncomeCount) IsSetWeek() bool {
	return p.Week != nil
}

func (p *IncomeCount) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IncomeCount(%+v)", *p)
}

var fieldIDToName_IncomeCount = map[int16]string{
	1: "month",
	2: "week",
}

type CreateDiaryRequest struct {
	Token   *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	Content *string `thrift:"content,2,optional" frugal:"2,optional,string" json:"content,omitempty"`
}

func NewCreateDiaryRequest() *CreateDiaryRequest {
	return &CreateDiaryRequest{}
}

func (p *CreateDiaryRequest) InitDefault() {
}

var CreateDiaryRequest_Token_DEFAULT string

func (p *CreateDiaryRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return CreateDiaryRequest_Token_DEFAULT
	}
	return *p.Token
}

var CreateDiaryRequest_Content_DEFAULT string

func (p *CreateDiaryRequest) GetContent() (v string) {
	if !p.IsSetContent() {
		return CreateDiaryRequest_Content_DEFAULT
	}
	return *p.Content
}
func (p *CreateDiaryRequest) SetToken(val *string) {
	p.Token = val
}
func (p *CreateDiaryRequest) SetContent(val *string) {
	p.Content = val
}

func (p *CreateDiaryRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *CreateDiaryRequest) IsSetContent() bool {
	return p.Content != nil
}

func (p *CreateDiaryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateDiaryRequest(%+v)", *p)
}

var fieldIDToName_CreateDiaryRequest = map[int16]string{
	1: "token",
	2: "content",
}

type CreateDiaryResponse struct {
	DiaryId  *string        `thrift:"diaryId,1,optional" frugal:"1,optional,string" json:"diaryId,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewCreateDiaryResponse() *CreateDiaryResponse {
	return &CreateDiaryResponse{}
}

func (p *CreateDiaryResponse) InitDefault() {
}

var CreateDiaryResponse_DiaryId_DEFAULT string

func (p *CreateDiaryResponse) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return CreateDiaryResponse_DiaryId_DEFAULT
	}
	return *p.DiaryId
}

var CreateDiaryResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CreateDiaryResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateDiaryResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateDiaryResponse) SetDiaryId(val *string) {
	p.DiaryId = val
}
func (p *CreateDiaryResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateDiaryResponse) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *CreateDiaryResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateDiaryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateDiaryResponse(%+v)", *p)
}

var fieldIDToName_CreateDiaryResponse = map[int16]string{
	1:   "diaryId",
	255: "BaseResp",
}

type UpdateDiaryRequest struct {
	Token   *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	Content *string `thrift:"content,2,optional" frugal:"2,optional,string" json:"content,omitempty"`
	DiaryId *string `thrift:"DiaryId,3,optional" frugal:"3,optional,string" json:"DiaryId,omitempty"`
}

func NewUpdateDiaryRequest() *UpdateDiaryRequest {
	return &UpdateDiaryRequest{}
}

func (p *UpdateDiaryRequest) InitDefault() {
}

var UpdateDiaryRequest_Token_DEFAULT string

func (p *UpdateDiaryRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return UpdateDiaryRequest_Token_DEFAULT
	}
	return *p.Token
}

var UpdateDiaryRequest_Content_DEFAULT string

func (p *UpdateDiaryRequest) GetContent() (v string) {
	if !p.IsSetContent() {
		return UpdateDiaryRequest_Content_DEFAULT
	}
	return *p.Content
}

var UpdateDiaryRequest_DiaryId_DEFAULT string

func (p *UpdateDiaryRequest) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return UpdateDiaryRequest_DiaryId_DEFAULT
	}
	return *p.DiaryId
}
func (p *UpdateDiaryRequest) SetToken(val *string) {
	p.Token = val
}
func (p *UpdateDiaryRequest) SetContent(val *string) {
	p.Content = val
}
func (p *UpdateDiaryRequest) SetDiaryId(val *string) {
	p.DiaryId = val
}

func (p *UpdateDiaryRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *UpdateDiaryRequest) IsSetContent() bool {
	return p.Content != nil
}

func (p *UpdateDiaryRequest) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *UpdateDiaryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDiaryRequest(%+v)", *p)
}

var fieldIDToName_UpdateDiaryRequest = map[int16]string{
	1: "token",
	2: "content",
	3: "DiaryId",
}

type UpdateDiaryResponse struct {
	DiaryId  *string        `thrift:"diaryId,1,optional" frugal:"1,optional,string" json:"diaryId,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewUpdateDiaryResponse() *UpdateDiaryResponse {
	return &UpdateDiaryResponse{}
}

func (p *UpdateDiaryResponse) InitDefault() {
}

var UpdateDiaryResponse_DiaryId_DEFAULT string

func (p *UpdateDiaryResponse) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return UpdateDiaryResponse_DiaryId_DEFAULT
	}
	return *p.DiaryId
}

var UpdateDiaryResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateDiaryResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateDiaryResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateDiaryResponse) SetDiaryId(val *string) {
	p.DiaryId = val
}
func (p *UpdateDiaryResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateDiaryResponse) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *UpdateDiaryResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateDiaryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDiaryResponse(%+v)", *p)
}

var fieldIDToName_UpdateDiaryResponse = map[int16]string{
	1:   "diaryId",
	255: "BaseResp",
}

type DeleteDiaryRequest struct {
	Token   *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	DiaryId *string `thrift:"diaryId,2,optional" frugal:"2,optional,string" json:"diaryId,omitempty"`
}

func NewDeleteDiaryRequest() *DeleteDiaryRequest {
	return &DeleteDiaryRequest{}
}

func (p *DeleteDiaryRequest) InitDefault() {
}

var DeleteDiaryRequest_Token_DEFAULT string

func (p *DeleteDiaryRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return DeleteDiaryRequest_Token_DEFAULT
	}
	return *p.Token
}

var DeleteDiaryRequest_DiaryId_DEFAULT string

func (p *DeleteDiaryRequest) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return DeleteDiaryRequest_DiaryId_DEFAULT
	}
	return *p.DiaryId
}
func (p *DeleteDiaryRequest) SetToken(val *string) {
	p.Token = val
}
func (p *DeleteDiaryRequest) SetDiaryId(val *string) {
	p.DiaryId = val
}

func (p *DeleteDiaryRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *DeleteDiaryRequest) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *DeleteDiaryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteDiaryRequest(%+v)", *p)
}

var fieldIDToName_DeleteDiaryRequest = map[int16]string{
	1: "token",
	2: "diaryId",
}

type DeleteDiaryResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewDeleteDiaryResponse() *DeleteDiaryResponse {
	return &DeleteDiaryResponse{}
}

func (p *DeleteDiaryResponse) InitDefault() {
}

var DeleteDiaryResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteDiaryResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteDiaryResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteDiaryResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteDiaryResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteDiaryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteDiaryResponse(%+v)", *p)
}

var fieldIDToName_DeleteDiaryResponse = map[int16]string{
	255: "BaseResp",
}

type QueryDiaryRequest struct {
	Token           *string `thrift:"token,1,optional" frugal:"1,optional,string" json:"token,omitempty"`
	PostStartTime   *string `thrift:"postStartTime,2,optional" frugal:"2,optional,string" json:"postStartTime,omitempty"`
	PostEndTime     *string `thrift:"postEndTime,3,optional" frugal:"3,optional,string" json:"postEndTime,omitempty"`
	UpdateStartTime *string `thrift:"updateStartTime,4,optional" frugal:"4,optional,string" json:"updateStartTime,omitempty"`
	UpdateEndTime   *string `thrift:"updateEndTime,5,optional" frugal:"5,optional,string" json:"updateEndTime,omitempty"`
	DiaryId         *string `thrift:"diaryId,6,optional" frugal:"6,optional,string" json:"diaryId,omitempty"`
	Page            *string `thrift:"page,7,optional" frugal:"7,optional,string" json:"page,omitempty"`
	Size            *string `thrift:"size,8,optional" frugal:"8,optional,string" json:"size,omitempty"`
}

func NewQueryDiaryRequest() *QueryDiaryRequest {
	return &QueryDiaryRequest{}
}

func (p *QueryDiaryRequest) InitDefault() {
}

var QueryDiaryRequest_Token_DEFAULT string

func (p *QueryDiaryRequest) GetToken() (v string) {
	if !p.IsSetToken() {
		return QueryDiaryRequest_Token_DEFAULT
	}
	return *p.Token
}

var QueryDiaryRequest_PostStartTime_DEFAULT string

func (p *QueryDiaryRequest) GetPostStartTime() (v string) {
	if !p.IsSetPostStartTime() {
		return QueryDiaryRequest_PostStartTime_DEFAULT
	}
	return *p.PostStartTime
}

var QueryDiaryRequest_PostEndTime_DEFAULT string

func (p *QueryDiaryRequest) GetPostEndTime() (v string) {
	if !p.IsSetPostEndTime() {
		return QueryDiaryRequest_PostEndTime_DEFAULT
	}
	return *p.PostEndTime
}

var QueryDiaryRequest_UpdateStartTime_DEFAULT string

func (p *QueryDiaryRequest) GetUpdateStartTime() (v string) {
	if !p.IsSetUpdateStartTime() {
		return QueryDiaryRequest_UpdateStartTime_DEFAULT
	}
	return *p.UpdateStartTime
}

var QueryDiaryRequest_UpdateEndTime_DEFAULT string

func (p *QueryDiaryRequest) GetUpdateEndTime() (v string) {
	if !p.IsSetUpdateEndTime() {
		return QueryDiaryRequest_UpdateEndTime_DEFAULT
	}
	return *p.UpdateEndTime
}

var QueryDiaryRequest_DiaryId_DEFAULT string

func (p *QueryDiaryRequest) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return QueryDiaryRequest_DiaryId_DEFAULT
	}
	return *p.DiaryId
}

var QueryDiaryRequest_Page_DEFAULT string

func (p *QueryDiaryRequest) GetPage() (v string) {
	if !p.IsSetPage() {
		return QueryDiaryRequest_Page_DEFAULT
	}
	return *p.Page
}

var QueryDiaryRequest_Size_DEFAULT string

func (p *QueryDiaryRequest) GetSize() (v string) {
	if !p.IsSetSize() {
		return QueryDiaryRequest_Size_DEFAULT
	}
	return *p.Size
}
func (p *QueryDiaryRequest) SetToken(val *string) {
	p.Token = val
}
func (p *QueryDiaryRequest) SetPostStartTime(val *string) {
	p.PostStartTime = val
}
func (p *QueryDiaryRequest) SetPostEndTime(val *string) {
	p.PostEndTime = val
}
func (p *QueryDiaryRequest) SetUpdateStartTime(val *string) {
	p.UpdateStartTime = val
}
func (p *QueryDiaryRequest) SetUpdateEndTime(val *string) {
	p.UpdateEndTime = val
}
func (p *QueryDiaryRequest) SetDiaryId(val *string) {
	p.DiaryId = val
}
func (p *QueryDiaryRequest) SetPage(val *string) {
	p.Page = val
}
func (p *QueryDiaryRequest) SetSize(val *string) {
	p.Size = val
}

func (p *QueryDiaryRequest) IsSetToken() bool {
	return p.Token != nil
}

func (p *QueryDiaryRequest) IsSetPostStartTime() bool {
	return p.PostStartTime != nil
}

func (p *QueryDiaryRequest) IsSetPostEndTime() bool {
	return p.PostEndTime != nil
}

func (p *QueryDiaryRequest) IsSetUpdateStartTime() bool {
	return p.UpdateStartTime != nil
}

func (p *QueryDiaryRequest) IsSetUpdateEndTime() bool {
	return p.UpdateEndTime != nil
}

func (p *QueryDiaryRequest) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *QueryDiaryRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *QueryDiaryRequest) IsSetSize() bool {
	return p.Size != nil
}

func (p *QueryDiaryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryDiaryRequest(%+v)", *p)
}

var fieldIDToName_QueryDiaryRequest = map[int16]string{
	1: "token",
	2: "postStartTime",
	3: "postEndTime",
	4: "updateStartTime",
	5: "updateEndTime",
	6: "diaryId",
	7: "page",
	8: "size",
}

type QueryDiaryResponse struct {
	DiaryList []*DiaryInfo   `thrift:"diaryList,1,optional" frugal:"1,optional,list<DiaryInfo>" json:"diaryList,omitempty"`
	Total     *string        `thrift:"total,2,optional" frugal:"2,optional,string" json:"total,omitempty"`
	BaseResp  *base.BaseResp `thrift:"BaseResp,255,optional" frugal:"255,optional,base.BaseResp" json:"BaseResp,omitempty"`
}

func NewQueryDiaryResponse() *QueryDiaryResponse {
	return &QueryDiaryResponse{}
}

func (p *QueryDiaryResponse) InitDefault() {
}

var QueryDiaryResponse_DiaryList_DEFAULT []*DiaryInfo

func (p *QueryDiaryResponse) GetDiaryList() (v []*DiaryInfo) {
	if !p.IsSetDiaryList() {
		return QueryDiaryResponse_DiaryList_DEFAULT
	}
	return p.DiaryList
}

var QueryDiaryResponse_Total_DEFAULT string

func (p *QueryDiaryResponse) GetTotal() (v string) {
	if !p.IsSetTotal() {
		return QueryDiaryResponse_Total_DEFAULT
	}
	return *p.Total
}

var QueryDiaryResponse_BaseResp_DEFAULT *base.BaseResp

func (p *QueryDiaryResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return QueryDiaryResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *QueryDiaryResponse) SetDiaryList(val []*DiaryInfo) {
	p.DiaryList = val
}
func (p *QueryDiaryResponse) SetTotal(val *string) {
	p.Total = val
}
func (p *QueryDiaryResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *QueryDiaryResponse) IsSetDiaryList() bool {
	return p.DiaryList != nil
}

func (p *QueryDiaryResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *QueryDiaryResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *QueryDiaryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryDiaryResponse(%+v)", *p)
}

var fieldIDToName_QueryDiaryResponse = map[int16]string{
	1:   "diaryList",
	2:   "total",
	255: "BaseResp",
}

type DiaryInfo struct {
	DiaryId    *string `thrift:"diaryId,1,optional" frugal:"1,optional,string" json:"diaryId,omitempty"`
	Content    *string `thrift:"content,2,optional" frugal:"2,optional,string" json:"content,omitempty"`
	PostTime   *string `thrift:"postTime,3,optional" frugal:"3,optional,string" json:"postTime,omitempty"`
	UpdateTime *string `thrift:"updateTime,4,optional" frugal:"4,optional,string" json:"updateTime,omitempty"`
}

func NewDiaryInfo() *DiaryInfo {
	return &DiaryInfo{}
}

func (p *DiaryInfo) InitDefault() {
}

var DiaryInfo_DiaryId_DEFAULT string

func (p *DiaryInfo) GetDiaryId() (v string) {
	if !p.IsSetDiaryId() {
		return DiaryInfo_DiaryId_DEFAULT
	}
	return *p.DiaryId
}

var DiaryInfo_Content_DEFAULT string

func (p *DiaryInfo) GetContent() (v string) {
	if !p.IsSetContent() {
		return DiaryInfo_Content_DEFAULT
	}
	return *p.Content
}

var DiaryInfo_PostTime_DEFAULT string

func (p *DiaryInfo) GetPostTime() (v string) {
	if !p.IsSetPostTime() {
		return DiaryInfo_PostTime_DEFAULT
	}
	return *p.PostTime
}

var DiaryInfo_UpdateTime_DEFAULT string

func (p *DiaryInfo) GetUpdateTime() (v string) {
	if !p.IsSetUpdateTime() {
		return DiaryInfo_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *DiaryInfo) SetDiaryId(val *string) {
	p.DiaryId = val
}
func (p *DiaryInfo) SetContent(val *string) {
	p.Content = val
}
func (p *DiaryInfo) SetPostTime(val *string) {
	p.PostTime = val
}
func (p *DiaryInfo) SetUpdateTime(val *string) {
	p.UpdateTime = val
}

func (p *DiaryInfo) IsSetDiaryId() bool {
	return p.DiaryId != nil
}

func (p *DiaryInfo) IsSetContent() bool {
	return p.Content != nil
}

func (p *DiaryInfo) IsSetPostTime() bool {
	return p.PostTime != nil
}

func (p *DiaryInfo) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *DiaryInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DiaryInfo(%+v)", *p)
}

var fieldIDToName_DiaryInfo = map[int16]string{
	1: "diaryId",
	2: "content",
	3: "postTime",
	4: "updateTime",
}

type ItemService interface {
	CommonLogin(ctx context.Context, req *CommonLoginRequest) (r *CommonLoginResponse, err error)

	CommonIsLogin(ctx context.Context, req *CommonIsLoginRequest) (r *CommonIsLoginResponse, err error)

	CommonUpdateUserInfo(ctx context.Context, req *CommonUpdateUserInfoRequest) (r *CommonUpdateUserInfoResponse, err error)

	CommonSignOut(ctx context.Context, req *CommonSignOutRequest) (r *CommonSignOutResponse, err error)

	CreateIncome(ctx context.Context, req *CreateIncomeRequest) (r *CreateIncomeResponse, err error)

	UpdateIncome(ctx context.Context, req *UpdateIncomeRequest) (r *UpdateIncomeResponse, err error)

	DeleteIncome(ctx context.Context, req *DeleteIncomeRequest) (r *DeleteIncomeResponse, err error)

	QueryIncome(ctx context.Context, req *QueryIncomeRequest) (r *QueryIncomeResponse, err error)

	CreateDiary(ctx context.Context, req *CreateDiaryRequest) (r *CreateDiaryResponse, err error)

	UpdateDiary(ctx context.Context, req *UpdateDiaryRequest) (r *UpdateDiaryResponse, err error)

	DeleteDiary(ctx context.Context, req *DeleteDiaryRequest) (r *DeleteDiaryResponse, err error)

	QueryDiary(ctx context.Context, req *QueryDiaryRequest) (r *QueryDiaryResponse, err error)
}

type ItemServiceCommonLoginArgs struct {
	Req *CommonLoginRequest `thrift:"req,1" frugal:"1,default,CommonLoginRequest" json:"req"`
}

func NewItemServiceCommonLoginArgs() *ItemServiceCommonLoginArgs {
	return &ItemServiceCommonLoginArgs{}
}

func (p *ItemServiceCommonLoginArgs) InitDefault() {
}

var ItemServiceCommonLoginArgs_Req_DEFAULT *CommonLoginRequest

func (p *ItemServiceCommonLoginArgs) GetReq() (v *CommonLoginRequest) {
	if !p.IsSetReq() {
		return ItemServiceCommonLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCommonLoginArgs) SetReq(val *CommonLoginRequest) {
	p.Req = val
}

func (p *ItemServiceCommonLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCommonLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonLoginArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonLoginArgs = map[int16]string{
	1: "req",
}

type ItemServiceCommonLoginResult struct {
	Success *CommonLoginResponse `thrift:"success,0,optional" frugal:"0,optional,CommonLoginResponse" json:"success,omitempty"`
}

func NewItemServiceCommonLoginResult() *ItemServiceCommonLoginResult {
	return &ItemServiceCommonLoginResult{}
}

func (p *ItemServiceCommonLoginResult) InitDefault() {
}

var ItemServiceCommonLoginResult_Success_DEFAULT *CommonLoginResponse

func (p *ItemServiceCommonLoginResult) GetSuccess() (v *CommonLoginResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCommonLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCommonLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonLoginResponse)
}

func (p *ItemServiceCommonLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCommonLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonLoginResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonLoginResult = map[int16]string{
	0: "success",
}

type ItemServiceCommonIsLoginArgs struct {
	Req *CommonIsLoginRequest `thrift:"req,1" frugal:"1,default,CommonIsLoginRequest" json:"req"`
}

func NewItemServiceCommonIsLoginArgs() *ItemServiceCommonIsLoginArgs {
	return &ItemServiceCommonIsLoginArgs{}
}

func (p *ItemServiceCommonIsLoginArgs) InitDefault() {
}

var ItemServiceCommonIsLoginArgs_Req_DEFAULT *CommonIsLoginRequest

func (p *ItemServiceCommonIsLoginArgs) GetReq() (v *CommonIsLoginRequest) {
	if !p.IsSetReq() {
		return ItemServiceCommonIsLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCommonIsLoginArgs) SetReq(val *CommonIsLoginRequest) {
	p.Req = val
}

func (p *ItemServiceCommonIsLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCommonIsLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonIsLoginArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonIsLoginArgs = map[int16]string{
	1: "req",
}

type ItemServiceCommonIsLoginResult struct {
	Success *CommonIsLoginResponse `thrift:"success,0,optional" frugal:"0,optional,CommonIsLoginResponse" json:"success,omitempty"`
}

func NewItemServiceCommonIsLoginResult() *ItemServiceCommonIsLoginResult {
	return &ItemServiceCommonIsLoginResult{}
}

func (p *ItemServiceCommonIsLoginResult) InitDefault() {
}

var ItemServiceCommonIsLoginResult_Success_DEFAULT *CommonIsLoginResponse

func (p *ItemServiceCommonIsLoginResult) GetSuccess() (v *CommonIsLoginResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCommonIsLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCommonIsLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonIsLoginResponse)
}

func (p *ItemServiceCommonIsLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCommonIsLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonIsLoginResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonIsLoginResult = map[int16]string{
	0: "success",
}

type ItemServiceCommonUpdateUserInfoArgs struct {
	Req *CommonUpdateUserInfoRequest `thrift:"req,1" frugal:"1,default,CommonUpdateUserInfoRequest" json:"req"`
}

func NewItemServiceCommonUpdateUserInfoArgs() *ItemServiceCommonUpdateUserInfoArgs {
	return &ItemServiceCommonUpdateUserInfoArgs{}
}

func (p *ItemServiceCommonUpdateUserInfoArgs) InitDefault() {
}

var ItemServiceCommonUpdateUserInfoArgs_Req_DEFAULT *CommonUpdateUserInfoRequest

func (p *ItemServiceCommonUpdateUserInfoArgs) GetReq() (v *CommonUpdateUserInfoRequest) {
	if !p.IsSetReq() {
		return ItemServiceCommonUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCommonUpdateUserInfoArgs) SetReq(val *CommonUpdateUserInfoRequest) {
	p.Req = val
}

func (p *ItemServiceCommonUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCommonUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type ItemServiceCommonUpdateUserInfoResult struct {
	Success *CommonUpdateUserInfoResponse `thrift:"success,0,optional" frugal:"0,optional,CommonUpdateUserInfoResponse" json:"success,omitempty"`
}

func NewItemServiceCommonUpdateUserInfoResult() *ItemServiceCommonUpdateUserInfoResult {
	return &ItemServiceCommonUpdateUserInfoResult{}
}

func (p *ItemServiceCommonUpdateUserInfoResult) InitDefault() {
}

var ItemServiceCommonUpdateUserInfoResult_Success_DEFAULT *CommonUpdateUserInfoResponse

func (p *ItemServiceCommonUpdateUserInfoResult) GetSuccess() (v *CommonUpdateUserInfoResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCommonUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCommonUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonUpdateUserInfoResponse)
}

func (p *ItemServiceCommonUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCommonUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type ItemServiceCommonSignOutArgs struct {
	Req *CommonSignOutRequest `thrift:"req,1" frugal:"1,default,CommonSignOutRequest" json:"req"`
}

func NewItemServiceCommonSignOutArgs() *ItemServiceCommonSignOutArgs {
	return &ItemServiceCommonSignOutArgs{}
}

func (p *ItemServiceCommonSignOutArgs) InitDefault() {
}

var ItemServiceCommonSignOutArgs_Req_DEFAULT *CommonSignOutRequest

func (p *ItemServiceCommonSignOutArgs) GetReq() (v *CommonSignOutRequest) {
	if !p.IsSetReq() {
		return ItemServiceCommonSignOutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCommonSignOutArgs) SetReq(val *CommonSignOutRequest) {
	p.Req = val
}

func (p *ItemServiceCommonSignOutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCommonSignOutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonSignOutArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonSignOutArgs = map[int16]string{
	1: "req",
}

type ItemServiceCommonSignOutResult struct {
	Success *CommonSignOutResponse `thrift:"success,0,optional" frugal:"0,optional,CommonSignOutResponse" json:"success,omitempty"`
}

func NewItemServiceCommonSignOutResult() *ItemServiceCommonSignOutResult {
	return &ItemServiceCommonSignOutResult{}
}

func (p *ItemServiceCommonSignOutResult) InitDefault() {
}

var ItemServiceCommonSignOutResult_Success_DEFAULT *CommonSignOutResponse

func (p *ItemServiceCommonSignOutResult) GetSuccess() (v *CommonSignOutResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCommonSignOutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCommonSignOutResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonSignOutResponse)
}

func (p *ItemServiceCommonSignOutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCommonSignOutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCommonSignOutResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCommonSignOutResult = map[int16]string{
	0: "success",
}

type ItemServiceCreateIncomeArgs struct {
	Req *CreateIncomeRequest `thrift:"req,1" frugal:"1,default,CreateIncomeRequest" json:"req"`
}

func NewItemServiceCreateIncomeArgs() *ItemServiceCreateIncomeArgs {
	return &ItemServiceCreateIncomeArgs{}
}

func (p *ItemServiceCreateIncomeArgs) InitDefault() {
}

var ItemServiceCreateIncomeArgs_Req_DEFAULT *CreateIncomeRequest

func (p *ItemServiceCreateIncomeArgs) GetReq() (v *CreateIncomeRequest) {
	if !p.IsSetReq() {
		return ItemServiceCreateIncomeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCreateIncomeArgs) SetReq(val *CreateIncomeRequest) {
	p.Req = val
}

func (p *ItemServiceCreateIncomeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCreateIncomeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCreateIncomeArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCreateIncomeArgs = map[int16]string{
	1: "req",
}

type ItemServiceCreateIncomeResult struct {
	Success *CreateIncomeResponse `thrift:"success,0,optional" frugal:"0,optional,CreateIncomeResponse" json:"success,omitempty"`
}

func NewItemServiceCreateIncomeResult() *ItemServiceCreateIncomeResult {
	return &ItemServiceCreateIncomeResult{}
}

func (p *ItemServiceCreateIncomeResult) InitDefault() {
}

var ItemServiceCreateIncomeResult_Success_DEFAULT *CreateIncomeResponse

func (p *ItemServiceCreateIncomeResult) GetSuccess() (v *CreateIncomeResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCreateIncomeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCreateIncomeResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateIncomeResponse)
}

func (p *ItemServiceCreateIncomeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCreateIncomeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCreateIncomeResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCreateIncomeResult = map[int16]string{
	0: "success",
}

type ItemServiceUpdateIncomeArgs struct {
	Req *UpdateIncomeRequest `thrift:"req,1" frugal:"1,default,UpdateIncomeRequest" json:"req"`
}

func NewItemServiceUpdateIncomeArgs() *ItemServiceUpdateIncomeArgs {
	return &ItemServiceUpdateIncomeArgs{}
}

func (p *ItemServiceUpdateIncomeArgs) InitDefault() {
}

var ItemServiceUpdateIncomeArgs_Req_DEFAULT *UpdateIncomeRequest

func (p *ItemServiceUpdateIncomeArgs) GetReq() (v *UpdateIncomeRequest) {
	if !p.IsSetReq() {
		return ItemServiceUpdateIncomeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceUpdateIncomeArgs) SetReq(val *UpdateIncomeRequest) {
	p.Req = val
}

func (p *ItemServiceUpdateIncomeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceUpdateIncomeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceUpdateIncomeArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceUpdateIncomeArgs = map[int16]string{
	1: "req",
}

type ItemServiceUpdateIncomeResult struct {
	Success *UpdateIncomeResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateIncomeResponse" json:"success,omitempty"`
}

func NewItemServiceUpdateIncomeResult() *ItemServiceUpdateIncomeResult {
	return &ItemServiceUpdateIncomeResult{}
}

func (p *ItemServiceUpdateIncomeResult) InitDefault() {
}

var ItemServiceUpdateIncomeResult_Success_DEFAULT *UpdateIncomeResponse

func (p *ItemServiceUpdateIncomeResult) GetSuccess() (v *UpdateIncomeResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceUpdateIncomeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceUpdateIncomeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateIncomeResponse)
}

func (p *ItemServiceUpdateIncomeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceUpdateIncomeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceUpdateIncomeResult(%+v)", *p)
}

var fieldIDToName_ItemServiceUpdateIncomeResult = map[int16]string{
	0: "success",
}

type ItemServiceDeleteIncomeArgs struct {
	Req *DeleteIncomeRequest `thrift:"req,1" frugal:"1,default,DeleteIncomeRequest" json:"req"`
}

func NewItemServiceDeleteIncomeArgs() *ItemServiceDeleteIncomeArgs {
	return &ItemServiceDeleteIncomeArgs{}
}

func (p *ItemServiceDeleteIncomeArgs) InitDefault() {
}

var ItemServiceDeleteIncomeArgs_Req_DEFAULT *DeleteIncomeRequest

func (p *ItemServiceDeleteIncomeArgs) GetReq() (v *DeleteIncomeRequest) {
	if !p.IsSetReq() {
		return ItemServiceDeleteIncomeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceDeleteIncomeArgs) SetReq(val *DeleteIncomeRequest) {
	p.Req = val
}

func (p *ItemServiceDeleteIncomeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceDeleteIncomeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceDeleteIncomeArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceDeleteIncomeArgs = map[int16]string{
	1: "req",
}

type ItemServiceDeleteIncomeResult struct {
	Success *DeleteIncomeResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteIncomeResponse" json:"success,omitempty"`
}

func NewItemServiceDeleteIncomeResult() *ItemServiceDeleteIncomeResult {
	return &ItemServiceDeleteIncomeResult{}
}

func (p *ItemServiceDeleteIncomeResult) InitDefault() {
}

var ItemServiceDeleteIncomeResult_Success_DEFAULT *DeleteIncomeResponse

func (p *ItemServiceDeleteIncomeResult) GetSuccess() (v *DeleteIncomeResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceDeleteIncomeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceDeleteIncomeResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteIncomeResponse)
}

func (p *ItemServiceDeleteIncomeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceDeleteIncomeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceDeleteIncomeResult(%+v)", *p)
}

var fieldIDToName_ItemServiceDeleteIncomeResult = map[int16]string{
	0: "success",
}

type ItemServiceQueryIncomeArgs struct {
	Req *QueryIncomeRequest `thrift:"req,1" frugal:"1,default,QueryIncomeRequest" json:"req"`
}

func NewItemServiceQueryIncomeArgs() *ItemServiceQueryIncomeArgs {
	return &ItemServiceQueryIncomeArgs{}
}

func (p *ItemServiceQueryIncomeArgs) InitDefault() {
}

var ItemServiceQueryIncomeArgs_Req_DEFAULT *QueryIncomeRequest

func (p *ItemServiceQueryIncomeArgs) GetReq() (v *QueryIncomeRequest) {
	if !p.IsSetReq() {
		return ItemServiceQueryIncomeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceQueryIncomeArgs) SetReq(val *QueryIncomeRequest) {
	p.Req = val
}

func (p *ItemServiceQueryIncomeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceQueryIncomeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceQueryIncomeArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceQueryIncomeArgs = map[int16]string{
	1: "req",
}

type ItemServiceQueryIncomeResult struct {
	Success *QueryIncomeResponse `thrift:"success,0,optional" frugal:"0,optional,QueryIncomeResponse" json:"success,omitempty"`
}

func NewItemServiceQueryIncomeResult() *ItemServiceQueryIncomeResult {
	return &ItemServiceQueryIncomeResult{}
}

func (p *ItemServiceQueryIncomeResult) InitDefault() {
}

var ItemServiceQueryIncomeResult_Success_DEFAULT *QueryIncomeResponse

func (p *ItemServiceQueryIncomeResult) GetSuccess() (v *QueryIncomeResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceQueryIncomeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceQueryIncomeResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryIncomeResponse)
}

func (p *ItemServiceQueryIncomeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceQueryIncomeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceQueryIncomeResult(%+v)", *p)
}

var fieldIDToName_ItemServiceQueryIncomeResult = map[int16]string{
	0: "success",
}

type ItemServiceCreateDiaryArgs struct {
	Req *CreateDiaryRequest `thrift:"req,1" frugal:"1,default,CreateDiaryRequest" json:"req"`
}

func NewItemServiceCreateDiaryArgs() *ItemServiceCreateDiaryArgs {
	return &ItemServiceCreateDiaryArgs{}
}

func (p *ItemServiceCreateDiaryArgs) InitDefault() {
}

var ItemServiceCreateDiaryArgs_Req_DEFAULT *CreateDiaryRequest

func (p *ItemServiceCreateDiaryArgs) GetReq() (v *CreateDiaryRequest) {
	if !p.IsSetReq() {
		return ItemServiceCreateDiaryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceCreateDiaryArgs) SetReq(val *CreateDiaryRequest) {
	p.Req = val
}

func (p *ItemServiceCreateDiaryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceCreateDiaryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCreateDiaryArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceCreateDiaryArgs = map[int16]string{
	1: "req",
}

type ItemServiceCreateDiaryResult struct {
	Success *CreateDiaryResponse `thrift:"success,0,optional" frugal:"0,optional,CreateDiaryResponse" json:"success,omitempty"`
}

func NewItemServiceCreateDiaryResult() *ItemServiceCreateDiaryResult {
	return &ItemServiceCreateDiaryResult{}
}

func (p *ItemServiceCreateDiaryResult) InitDefault() {
}

var ItemServiceCreateDiaryResult_Success_DEFAULT *CreateDiaryResponse

func (p *ItemServiceCreateDiaryResult) GetSuccess() (v *CreateDiaryResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceCreateDiaryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceCreateDiaryResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateDiaryResponse)
}

func (p *ItemServiceCreateDiaryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceCreateDiaryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceCreateDiaryResult(%+v)", *p)
}

var fieldIDToName_ItemServiceCreateDiaryResult = map[int16]string{
	0: "success",
}

type ItemServiceUpdateDiaryArgs struct {
	Req *UpdateDiaryRequest `thrift:"req,1" frugal:"1,default,UpdateDiaryRequest" json:"req"`
}

func NewItemServiceUpdateDiaryArgs() *ItemServiceUpdateDiaryArgs {
	return &ItemServiceUpdateDiaryArgs{}
}

func (p *ItemServiceUpdateDiaryArgs) InitDefault() {
}

var ItemServiceUpdateDiaryArgs_Req_DEFAULT *UpdateDiaryRequest

func (p *ItemServiceUpdateDiaryArgs) GetReq() (v *UpdateDiaryRequest) {
	if !p.IsSetReq() {
		return ItemServiceUpdateDiaryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceUpdateDiaryArgs) SetReq(val *UpdateDiaryRequest) {
	p.Req = val
}

func (p *ItemServiceUpdateDiaryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceUpdateDiaryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceUpdateDiaryArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceUpdateDiaryArgs = map[int16]string{
	1: "req",
}

type ItemServiceUpdateDiaryResult struct {
	Success *UpdateDiaryResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateDiaryResponse" json:"success,omitempty"`
}

func NewItemServiceUpdateDiaryResult() *ItemServiceUpdateDiaryResult {
	return &ItemServiceUpdateDiaryResult{}
}

func (p *ItemServiceUpdateDiaryResult) InitDefault() {
}

var ItemServiceUpdateDiaryResult_Success_DEFAULT *UpdateDiaryResponse

func (p *ItemServiceUpdateDiaryResult) GetSuccess() (v *UpdateDiaryResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceUpdateDiaryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceUpdateDiaryResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateDiaryResponse)
}

func (p *ItemServiceUpdateDiaryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceUpdateDiaryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceUpdateDiaryResult(%+v)", *p)
}

var fieldIDToName_ItemServiceUpdateDiaryResult = map[int16]string{
	0: "success",
}

type ItemServiceDeleteDiaryArgs struct {
	Req *DeleteDiaryRequest `thrift:"req,1" frugal:"1,default,DeleteDiaryRequest" json:"req"`
}

func NewItemServiceDeleteDiaryArgs() *ItemServiceDeleteDiaryArgs {
	return &ItemServiceDeleteDiaryArgs{}
}

func (p *ItemServiceDeleteDiaryArgs) InitDefault() {
}

var ItemServiceDeleteDiaryArgs_Req_DEFAULT *DeleteDiaryRequest

func (p *ItemServiceDeleteDiaryArgs) GetReq() (v *DeleteDiaryRequest) {
	if !p.IsSetReq() {
		return ItemServiceDeleteDiaryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceDeleteDiaryArgs) SetReq(val *DeleteDiaryRequest) {
	p.Req = val
}

func (p *ItemServiceDeleteDiaryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceDeleteDiaryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceDeleteDiaryArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceDeleteDiaryArgs = map[int16]string{
	1: "req",
}

type ItemServiceDeleteDiaryResult struct {
	Success *DeleteDiaryResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteDiaryResponse" json:"success,omitempty"`
}

func NewItemServiceDeleteDiaryResult() *ItemServiceDeleteDiaryResult {
	return &ItemServiceDeleteDiaryResult{}
}

func (p *ItemServiceDeleteDiaryResult) InitDefault() {
}

var ItemServiceDeleteDiaryResult_Success_DEFAULT *DeleteDiaryResponse

func (p *ItemServiceDeleteDiaryResult) GetSuccess() (v *DeleteDiaryResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceDeleteDiaryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceDeleteDiaryResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteDiaryResponse)
}

func (p *ItemServiceDeleteDiaryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceDeleteDiaryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceDeleteDiaryResult(%+v)", *p)
}

var fieldIDToName_ItemServiceDeleteDiaryResult = map[int16]string{
	0: "success",
}

type ItemServiceQueryDiaryArgs struct {
	Req *QueryDiaryRequest `thrift:"req,1" frugal:"1,default,QueryDiaryRequest" json:"req"`
}

func NewItemServiceQueryDiaryArgs() *ItemServiceQueryDiaryArgs {
	return &ItemServiceQueryDiaryArgs{}
}

func (p *ItemServiceQueryDiaryArgs) InitDefault() {
}

var ItemServiceQueryDiaryArgs_Req_DEFAULT *QueryDiaryRequest

func (p *ItemServiceQueryDiaryArgs) GetReq() (v *QueryDiaryRequest) {
	if !p.IsSetReq() {
		return ItemServiceQueryDiaryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ItemServiceQueryDiaryArgs) SetReq(val *QueryDiaryRequest) {
	p.Req = val
}

func (p *ItemServiceQueryDiaryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ItemServiceQueryDiaryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceQueryDiaryArgs(%+v)", *p)
}

var fieldIDToName_ItemServiceQueryDiaryArgs = map[int16]string{
	1: "req",
}

type ItemServiceQueryDiaryResult struct {
	Success *QueryDiaryResponse `thrift:"success,0,optional" frugal:"0,optional,QueryDiaryResponse" json:"success,omitempty"`
}

func NewItemServiceQueryDiaryResult() *ItemServiceQueryDiaryResult {
	return &ItemServiceQueryDiaryResult{}
}

func (p *ItemServiceQueryDiaryResult) InitDefault() {
}

var ItemServiceQueryDiaryResult_Success_DEFAULT *QueryDiaryResponse

func (p *ItemServiceQueryDiaryResult) GetSuccess() (v *QueryDiaryResponse) {
	if !p.IsSetSuccess() {
		return ItemServiceQueryDiaryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ItemServiceQueryDiaryResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryDiaryResponse)
}

func (p *ItemServiceQueryDiaryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemServiceQueryDiaryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemServiceQueryDiaryResult(%+v)", *p)
}

var fieldIDToName_ItemServiceQueryDiaryResult = map[int16]string{
	0: "success",
}
